/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fees_management_system;

import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.PrintJob;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;




/**
 *
 * @author hp
 */
public class PrintReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        initComponents();
        getRecords();
        Container c=getContentPane();
        c.setBackground(new Color(0,153,153));
    }
    public void getRecords()
    {
        try
        {
            Connection con=DBConnection.getConnection();
            PreparedStatement pst= con.prepareStatement("select * from fees_details order by reciept_no desc fetch first 1 rows only");
            
            ResultSet rs= pst.executeQuery();
            rs.next();
            
            txt_receiptNo.setText(rs.getString("reciept_no"));
            
            txt_paymentMode.setText(rs.getString("payment_mode"));
            String paymentMode=rs.getString("payment_mode");
            
            if(paymentMode.equalsIgnoreCase("cash"))
            {
                lbl_cheque_Dd.setText("cheque No");
                txt_cheque_dd.setText("-");
                txt_bankName.setText("-");
                
            }
            if(paymentMode.equalsIgnoreCase("cheque"))
            {
                lbl_cheque_Dd.setText("Cheque No");
                txt_cheque_dd.setText(rs.getString("cheque_no"));
                txt_bankName.setText(rs.getString("bank_name"));
                
            }
             if(paymentMode.equalsIgnoreCase("dd"))
            {
                lbl_cheque_Dd.setText("DD No");
                txt_cheque_dd.setText(rs.getString("dd_no"));
                txt_bankName.setText(rs.getString("bank_name"));
                
            }
             if(paymentMode.equalsIgnoreCase("card"))
            {
                lbl_cheque_Dd.setText("Cheque No");
                txt_cheque_dd.setText("-");
                txt_bankName.setText(rs.getString("bank_name"));
                
            }
             txt_receivedFrom.setText(rs.getString("student_name"));
             txt_date.setText(rs.getString("date"));
             txt_gstin.setText(rs.getString("gstin"));
             txt_year1.setText(rs.getString("year1"));
              txt_year2.setText(rs.getString("year2"));
              
               txt_initialAmount.setText(rs.getString("amount"));
               txt_cgst.setText(rs.getString("cgst"));
                txt_sgst.setText(rs.getString("sgst"));
                 txt_total.setText(rs.getString("total_amount"));
                  txt_totalInWords.setText(rs.getString("total_in_words"));
                  txt_remark.setText(rs.getString("remark"));
                  
               
               
          
            
        }
        catch(Exception e)
        {
           e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsideBar = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        btnSearch = new javax.swing.JLabel();
        panelEdit = new javax.swing.JPanel();
        btnEdit = new javax.swing.JLabel();
        panelGamesList = new javax.swing.JPanel();
        btnGamesList = new javax.swing.JLabel();
        panelViewAllRecords = new javax.swing.JPanel();
        btnViewAllRecord = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        panelLogout1 = new javax.swing.JPanel();
        btn_print = new javax.swing.JLabel();
        btn_edit = new javax.swing.JPanel();
        btn_print1 = new javax.swing.JLabel();
        panel_print = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_paymentMode = new javax.swing.JLabel();
        txt_cheque_dd = new javax.swing.JLabel();
        lbl_DDno1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_paymentMode1 = new javax.swing.JLabel();
        lbl_cheque_Dd = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_receivedFrom = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        lbl_DDno7 = new javax.swing.JLabel();
        txt_bankName = new javax.swing.JLabel();
        txt_receiptNo = new javax.swing.JLabel();
        txt_gstin = new javax.swing.JLabel();
        txt_receiptNo3 = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        lbl_DDno8 = new javax.swing.JLabel();
        txt_receiptNo4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_DDno9 = new javax.swing.JLabel();
        lbl_DDno10 = new javax.swing.JLabel();
        txt_sgst = new javax.swing.JLabel();
        lbl_bankName = new javax.swing.JLabel();
        lbl_DDno13 = new javax.swing.JLabel();
        txt_initialAmount = new javax.swing.JLabel();
        txt_cgst = new javax.swing.JLabel();
        txt_courseName2 = new javax.swing.JLabel();
        txt_cgst1 = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_totalInWords = new javax.swing.JLabel();
        txt_sgst3 = new javax.swing.JLabel();
        txt_remark = new javax.swing.JLabel();
        txt_total1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_sgst5 = new javax.swing.JLabel();
        txt_sgst6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome.setEnabled(false);
        panelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelHomeMouseExited(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnHome.setText("  Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        panelsideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 70));

        panelSearch.setBackground(new java.awt.Color(0, 102, 102));
        panelSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelSearch.setEnabled(false);
        panelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSearchMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSearchMouseExited(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btnSearch.setText("Search Record");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        panelsideBar.add(panelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        panelEdit.setBackground(new java.awt.Color(0, 102, 102));
        panelEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelEdit.setEnabled(false);
        panelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEditMouseExited(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btnEdit.setText(" Edit Games");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelEditLayout = new javax.swing.GroupLayout(panelEdit);
        panelEdit.setLayout(panelEditLayout);
        panelEditLayout.setHorizontalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        panelEditLayout.setVerticalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelsideBar.add(panelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        panelGamesList.setBackground(new java.awt.Color(0, 102, 102));
        panelGamesList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelGamesList.setEnabled(false);
        panelGamesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelGamesListMouseExited(evt);
            }
        });

        btnGamesList.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnGamesList.setForeground(new java.awt.Color(255, 255, 255));
        btnGamesList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/list_1.png"))); // NOI18N
        btnGamesList.setText("Games List");
        btnGamesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGamesListMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelGamesListLayout = new javax.swing.GroupLayout(panelGamesList);
        panelGamesList.setLayout(panelGamesListLayout);
        panelGamesListLayout.setHorizontalGroup(
            panelGamesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGamesListLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnGamesList, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelGamesListLayout.setVerticalGroup(
            panelGamesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGamesList, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelsideBar.add(panelGamesList, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        panelViewAllRecords.setBackground(new java.awt.Color(0, 102, 102));
        panelViewAllRecords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelViewAllRecords.setEnabled(false);
        panelViewAllRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelViewAllRecordsMouseExited(evt);
            }
        });

        btnViewAllRecord.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnViewAllRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btnViewAllRecord.setText("View All Record ");
        btnViewAllRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewAllRecordMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelViewAllRecordsLayout = new javax.swing.GroupLayout(panelViewAllRecords);
        panelViewAllRecords.setLayout(panelViewAllRecordsLayout);
        panelViewAllRecordsLayout.setHorizontalGroup(
            panelViewAllRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewAllRecordsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnViewAllRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelViewAllRecordsLayout.setVerticalGroup(
            panelViewAllRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnViewAllRecord, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        panelsideBar.add(panelViewAllRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        panelBack.setBackground(new java.awt.Color(0, 102, 102));
        panelBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelBack.setEnabled(false);
        panelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBackMouseExited(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/left-arrow.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelBackLayout = new javax.swing.GroupLayout(panelBack);
        panelBack.setLayout(panelBackLayout);
        panelBackLayout.setHorizontalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        panelBackLayout.setVerticalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelsideBar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        panelLogout.setBackground(new java.awt.Color(0, 102, 102));
        panelLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelLogout.setEnabled(false);
        panelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLogoutMouseExited(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btnLogout.setText(" Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelLogoutLayout = new javax.swing.GroupLayout(panelLogout);
        panelLogout.setLayout(panelLogoutLayout);
        panelLogoutLayout.setHorizontalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        panelLogoutLayout.setVerticalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutLayout.createSequentialGroup()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        panelsideBar.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        panelLogout1.setBackground(new java.awt.Color(0, 102, 102));
        panelLogout1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelLogout1.setEnabled(false);
        panelLogout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLogout1MouseExited(evt);
            }
        });

        btn_print.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/printer-.png"))); // NOI18N
        btn_print.setText("  Print");
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_printMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelLogout1Layout = new javax.swing.GroupLayout(panelLogout1);
        panelLogout1.setLayout(panelLogout1Layout);
        panelLogout1Layout.setHorizontalGroup(
            panelLogout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogout1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        panelLogout1Layout.setVerticalGroup(
            panelLogout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogout1Layout.createSequentialGroup()
                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        panelsideBar.add(panelLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        btn_edit.setBackground(new java.awt.Color(0, 102, 102));
        btn_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btn_edit.setEnabled(false);
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
        });

        btn_print1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_print1.setForeground(new java.awt.Color(255, 255, 255));
        btn_print1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btn_print1.setText(" Edit");
        btn_print1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_print1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btn_editLayout = new javax.swing.GroupLayout(btn_edit);
        btn_edit.setLayout(btn_editLayout);
        btn_editLayout.setHorizontalGroup(
            btn_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_editLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btn_print1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        btn_editLayout.setVerticalGroup(
            btn_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_editLayout.createSequentialGroup()
                .addComponent(btn_print1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        panelsideBar.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, -1));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 1040));

        panel_print.setBackground(new java.awt.Color(255, 255, 255));
        panel_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MASTER MARTIAL ARTS ACADEMY");
        panel_print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 460, -1));

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel2.setText("Gundu Uppalavadi (Near Auto Stand)");
        panel_print.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel11.setText("Cuddalore");
        panel_print.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/download.png"))); // NOI18N
        panel_print.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 200, 170));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panel_print.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1220, 10));

        txt_paymentMode.setText("Mode of Payment :");
        panel_print.add(txt_paymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        txt_cheque_dd.setText("Cheque_dd");
        panel_print.add(txt_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        lbl_DDno1.setText("to");
        panel_print.add(lbl_DDno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 30, 30));

        jLabel5.setText("Receipt No :     MMAA-");
        panel_print.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        txt_paymentMode1.setText("Mode of Payment :");
        panel_print.add(txt_paymentMode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        lbl_cheque_Dd.setText("Cheque_dd");
        panel_print.add(lbl_cheque_Dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel7.setText("The following payments MMAA for the year :");
        panel_print.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 230, -1));

        txt_receivedFrom.setText("Received From :");
        panel_print.add(txt_receivedFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 200, -1));

        txt_year1.setText("21");
        panel_print.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 30, 30));

        txt_year2.setText("22");
        panel_print.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 30, 30));

        lbl_DDno7.setText("Received From :");
        panel_print.add(lbl_DDno7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 90, -1));

        txt_bankName.setText("Bank Name :");
        panel_print.add(txt_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 90, -1));

        txt_receiptNo.setText("Receipt no :   ");
        panel_print.add(txt_receiptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        txt_gstin.setText("GSTIN :");
        panel_print.add(txt_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));

        txt_receiptNo3.setText("Date :");
        panel_print.add(txt_receiptNo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, -1));

        txt_date.setText("Date :");
        panel_print.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        lbl_DDno8.setText("Amount(rs)");
        panel_print.add(lbl_DDno8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, 110, -1));

        txt_receiptNo4.setText("GSTIN :");
        panel_print.add(txt_receiptNo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));
        panel_print.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, 210, 20));
        panel_print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1220, 20));

        lbl_DDno9.setText("SL. No");
        panel_print.add(lbl_DDno9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 110, -1));

        lbl_DDno10.setText("Head");
        panel_print.add(lbl_DDno10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 110, -1));

        txt_sgst.setText("sgst");
        panel_print.add(txt_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 90, -1));

        lbl_bankName.setText("Bank Name :");
        panel_print.add(lbl_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 90, -1));

        lbl_DDno13.setText("1");
        panel_print.add(lbl_DDno13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 90, -1));

        txt_initialAmount.setText("1");
        panel_print.add(txt_initialAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 510, 90, -1));

        txt_cgst.setText("cgst");
        panel_print.add(txt_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, 90, -1));

        txt_courseName2.setText("1");
        panel_print.add(txt_courseName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 90, -1));

        txt_cgst1.setText("cgst(9 %)");
        panel_print.add(txt_cgst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 90, 20));

        txt_total.setText("Receiver Signature");
        panel_print.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 660, 150, -1));
        panel_print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 1220, 20));

        txt_totalInWords.setText("Total in words :");
        panel_print.add(txt_totalInWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 620, 280, -1));

        txt_sgst3.setText("sgst(9 %)");
        panel_print.add(txt_sgst3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 90, -1));

        txt_remark.setText("Remark :");
        panel_print.add(txt_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 650, 90, -1));

        txt_total1.setText("total");
        panel_print.add(txt_total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 620, 90, -1));
        panel_print.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 600, 260, 20));

        txt_sgst5.setText("Total in words :");
        panel_print.add(txt_sgst5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 90, -1));

        txt_sgst6.setText("Remark :");
        panel_print.add(txt_sgst6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 12)); // NOI18N
        jLabel3.setText("PRINT RECEIPT");
        panel_print.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        getContentPane().add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 1280, 860));

        setSize(new java.awt.Dimension(1979, 1131));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered

        Color clr=new Color(0,153,153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        Color clr=new Color(0,103,103);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseExited

    private void panelHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHomeMouseExited

        Color clr=new Color(0,153,153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_panelHomeMouseExited

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchMouseEntered

    private void panelSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchMouseClicked

    }//GEN-LAST:event_panelSearchMouseClicked

    private void panelSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSearchMouseExited

    }//GEN-LAST:event_panelSearchMouseExited

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMouseEntered

    private void panelEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEditMouseExited

    private void btnGamesListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGamesListMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGamesListMouseEntered

    private void panelGamesListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGamesListMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelGamesListMouseExited

    private void btnViewAllRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllRecordMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewAllRecordMouseEntered

    private void panelViewAllRecordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewAllRecordsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelViewAllRecordsMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseEntered

    private void panelBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBackMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelBackMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void panelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelLogoutMouseExited

    private void btn_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_printMouseEntered

    private void panelLogout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogout1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelLogout1MouseExited

    private void btn_print1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_print1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_print1MouseEntered

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editMouseExited

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable() {
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panel_print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }

    }//GEN-LAST:event_btn_printMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        home h=new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnGamesList;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnViewAllRecord;
    private javax.swing.JPanel btn_edit;
    private javax.swing.JLabel btn_print;
    private javax.swing.JLabel btn_print1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_DDno1;
    private javax.swing.JLabel lbl_DDno10;
    private javax.swing.JLabel lbl_DDno13;
    private javax.swing.JLabel lbl_DDno7;
    private javax.swing.JLabel lbl_DDno8;
    private javax.swing.JLabel lbl_DDno9;
    private javax.swing.JLabel lbl_bankName;
    private javax.swing.JLabel lbl_cheque_Dd;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JPanel panelGamesList;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelLogout1;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panelViewAllRecords;
    private javax.swing.JPanel panel_print;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JLabel txt_bankName;
    private javax.swing.JLabel txt_cgst;
    private javax.swing.JLabel txt_cgst1;
    private javax.swing.JLabel txt_cheque_dd;
    private javax.swing.JLabel txt_courseName2;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_gstin;
    private javax.swing.JLabel txt_initialAmount;
    private javax.swing.JLabel txt_paymentMode;
    private javax.swing.JLabel txt_paymentMode1;
    private javax.swing.JLabel txt_receiptNo;
    private javax.swing.JLabel txt_receiptNo3;
    private javax.swing.JLabel txt_receiptNo4;
    private javax.swing.JLabel txt_receivedFrom;
    private javax.swing.JLabel txt_remark;
    private javax.swing.JLabel txt_sgst;
    private javax.swing.JLabel txt_sgst3;
    private javax.swing.JLabel txt_sgst5;
    private javax.swing.JLabel txt_sgst6;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_total1;
    private javax.swing.JLabel txt_totalInWords;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
